USE master;
GO

IF EXISTS(select * from sys.databases where name = 'TERLETSKIY_ANDREY')
DROP DATABASE TERLETSKIY_ANDREY;

CREATE DATABASE TERLETSKIY_ANDREY;
GO

USE TERLETSKIY_ANDREY;
GO

CREATE SCHEMA sales;
GO

CREATE SCHEMA persons;
GO

CREATE TABLE sales.Orders (OrderNum INT NULL);

BACKUP DATABASE TERLETSKIY_ANDREY
TO DISK = 'D:\TERLETSKIY_ANDREY.bak';


USE master;
GO
DROP DATABASE TERLETSKIY_ANDREY;

RESTORE DATABASE TERLETSKIY_ANDREY
FROM DISK = 'D:\TERLETSKIY_ANDREY.bak';